### ISSUE TITLE
Training with different Font

### ISSUE THREAD

**Issue by MicahTWilson** [garnele007/SwiftOCR#1]
Hey, I'm trying to train the network with a font other than Arial and it doesn't seem to be working. Any help?

**Comment by garnele007** [comment]
If you want to train another font, i would replace (in the SwiftOCR.swift file) `internal let network = FFNN.fromFile(...` with `internal let network =  FFNN(inputs: 321, hidden: 100, outputs: 36, learningRate: 0.7, momentum: 0.4, weights: nil, activationFunction: .Sigmoid, errorFunction: .CrossEntropy(average: false))` and try it again. 
Maybe it will help if you set the errorThreshold in `trainWithCharSet` to a bigger number. Last but not least you have to set the path of your OCR-Network file in `saveOCR`.

Good luck :D

**Comment by MicahTWilson** [comment]
Okay I wasn't doing that first part! Thanks, I'm excited for the project! Good work!

**Comment by MicahTWilson** [comment]
Hey Nicolas,

Another question for you, my main goal with this is to get the OCR to be able to read 7-Segment fonts. I noticed when looking through the code that this is extremely difficult because of the way it processes the images into separate characters. I would love to be able to use your project to read digital scales. This is the font I'm trying to get to to work with and ones similar to it. http://www.dafont.com/digital-7.font Let me know if there is anything I can do to get this working, or if I should look elsewhere. Thanks

**Comment by garnele007** [comment]
In the extractBlobs function there are two variables called `xMergeRadius` and `yMergeRadius`. They are used to enlarge the merging radius of the detected blobs. If you set the `yMergeRadius` to 10, the bounding boxes of all detected blobs will be extended by 10 in the y dimension and if two bounding boxes are overlapping they get merged into one big bounding box. In your case I would increase the `yMergeRadius`.
![example merge](https://cloud.githubusercontent.com/assets/9914734/14795910/faea6d94-0b2a-11e6-838d-c1cc5fa5057e.jpg)
.
