### ISSUE TITLE
Japanese & Chinese hieroglyphs

### ISSUE THREAD

**Issue by zkenes** [garnele007/SwiftOCR#10]
Hi. 
Thanks for this awesome project and your work. And I have a question, Are you planning to implement recognition of hieroglyphs? It'd be so appreciated

**Comment by garnele007** [comment]
There are a few problems with hieroglyphs. First there are to many. If you only want to train 100 characters, it would be pretty easy but if you would want to recognize more it begins getting hard. Another problem is, the more characters you want to recognize, the slower recognition gets.

I tried training using 150 chinese characters and got an accuracy of about 70%. So it is possible to recognize hieroglyphs but the accuracy is bad. Sorry.
