### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by rwalt04** [garnele007/SwiftOCR#104]
I get these errors when trying run the build.  

Cannot invoke 'draw' with an argument list of type '(in: CGRect, withAttributes: [NSAttributedStringKey : Any])’

   NSString(string: code).draw(in: CGRect(origin: CGPoint(x: 0 + randomFloat(5), y: -15.5 + randomFloat(5)), size: randomImg.size), withAttributes: randomFontAttributes())

Type 'NSString' has no member 'font'
return [.font: randomFont(),
                    .kern: CGFloat(8) as NSObject,
                    .foregroundColor: OCRColor(red: 27/255 + randomFloat(0.2), green: 16/255 + randomFloat(0.2), blue: 16/255 + randomFloat(0.2), alpha: 80/100 + randomFloat(0.2)),
                    .paragraphStyle: paragraphStyle]
        }

**Comment by lgryp** [comment]
I'm having the same issue.
Is it related to Swift 4 or IOS 11?

**Comment by rwalt04** [comment]
Both I can’t figure away around

**Comment by lgryp** [comment]
I solved the issue by selecting Swift 4.0 syntax in the xcode build settings of my project.
Before, it was on Swift 3.2.

**Comment by ColdLogical** [comment]
For anyone who had a tough time finding this:

1. Click your project file
1. Click your target
1. Click `Build Settings`
1. Search `Swift Language Version`
1. Change to `Swift 4.0`

**Comment by frakman1** [comment]
I don't have the option to switch Swift versions. My XCode 8.3.3 only supports up to Swift 3.

![image](https://user-images.githubusercontent.com/5826484/32196704-e840bed4-bd97-11e7-93e2-44027c2f3485.png)

My error is slightly different:
in SwiftOCRTraining.swift:

![image](https://user-images.githubusercontent.com/5826484/32196749-0b1f70e4-bd98-11e7-8f6e-d175016d3715.png)

SwiftOCRTraining.swift:92:42: Use of undeclared type 'NSAttributedStringKey'

I tried changing it to `NSFontAttributeName` but I get the same error.
