### ISSUE TITLE
Recognizing special characters and periods 

### ISSUE THREAD

**Issue by scubess** [garnele007/SwiftOCR#112]
@garnele007 Thanks for your swiftOCR and it's working incredibly well! I am converting an image like “// TEXT.TEXT”. It does recognise the characters and provide output TEXTTEXT 

But, I want to include . and (or)  / in the list of recognition characters! So that it produce the output like “TEXT.TEXT” as exactly shown on the image. 

Could you let me know if this is possible please ?

**Comment by PapaHenson** [comment]
Could you parse the words and then add a period in between them?

**Comment by scubess** [comment]
@PapaHenson Sorry for my late reply. I dont think it will work for me.. because i am trying to scan live camera feed and if i have a single line or multi lines with some other texts , it will provide wrong output if i parse and add period between them.
if i scan something like this, "sample text //text.text and the invoice #//text more text"...it not possible to get the right text out.

**Comment by scubess** [comment]
Garnele clearly mentioned as of now recognizing short, one line long alphanumeric codes. Means i cannot expect more from swiftOCR at the moment. Will wait for update
