### ISSUE TITLE
Use submodules instead of direct frameworks.

### ISSUE THREAD

**Issue by ninjaprawn** [garnele007/SwiftOCR#13]
If by any chance these included frameworks were updated, then you wouldn't have to worry about manually updating them.

Also it sets the repo language to a greater percentage of Swift than Objective-C.

**Comment by garnele007** [comment]
Sorry for me taking so long to respond. I did take a look at submodules but is seams like they are a big hassle to work with. Maybe I will use subtrees in the future, but for now I'm going to continue using direct frameworks. (Also I fixed the repo language using the `.gitattributes` file)
