### ISSUE TITLE
Unable to build iOS and OSX examples

### ISSUE THREAD

**Issue by microspino** [garnele007/SwiftOCR#15]
I get the same error when i try to build the examples. See below:
![schermata 2016-05-12 alle 15 30 42](https://cloud.githubusercontent.com/assets/92588/15216264/bd7a41e4-1856-11e6-96c3-e87ec8baf794.png)

Any clue?

_Yosemite 10.10.5, XCode Version 7.2.1 (7C1002)_

**Comment by garnele007** [comment]
I think the problem is, that you are using Xcode 7.2.1. Associatedtype was introduced in Swift 2.2 (Xcode 7.3). To fix this problem you have to replace `associatedtype StorageType` with `typealias StorageType`.

**Comment by microspino** [comment]
Worked thx.
