### ISSUE TITLE
Fragment Shader Exception

### ISSUE THREAD

**Issue by dylib** [garnele007/SwiftOCR#16]
On `OS X` I get an exception immediately after dragging an image into the window:

**GPUImage`runSynchronouslyOnVideoProcessingQueue**
```
Failed to compile fragment shader
Program link log: (null)
Fragment shader compile log: ERROR: 0:25: 'vec2' : syntax error: syntax error
Vertex shader compile log: (null)
*** Assertion failure in -[GPUImageSingleComponentGaussianBlurFilter switchToVertexShader:fragmentShader:], /SwiftOCR/framework/SwiftOCR/GPUImage-master/framework/Source/GPUImageGaussianBlurFilter.m:401
An uncaught exception was raised
Filter shader link failed
```
I didn't manage to track down which `vec2` it was (1503 results in 128 files)

**Comment by garnele007** [comment]
It was caused by the GPUImageSingleComponentGaussianBlurFilter. Setting the blur radius to a number bigger than 7 (i think) caused it to crash.
