### ISSUE TITLE
Dependency managers

### ISSUE THREAD

**Issue by orxelm** [garnele007/SwiftOCR#17]
Hi
It will be great if you can support Cocoapods/Carthage.

Thanks!

**Comment by TofPlay** [comment]
For Carthage take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://realm.io/news/swift-dependency-management-with-carthage/)
- [Carthage Tutorial: Getting Started](https://www.raywenderlich.com/109330/carthage-tutorial-getting-started)
- [Making Carthage-compatible Frameworks with Swift](http://blog.mat.tc/how-to-make-a-carthage-compatible-framework/)
- [Creating Cross-Platform Swift Frameworks for iOS, watchOS, and tvOS via Carthage and CocoaPods] (http://basememara.com/creating-cross-platform-swift-frameworks-ios-watchos-tvos-via-carthage-cocoapods/)

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-compatible-4BC51D.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by garnele007** [comment]
I added support for Carthage. Will try to add Cocoapods too.

**Comment by orxelm** [comment]
Great, Thanks!

Let me know if you need any help.
