### ISSUE TITLE
Help on blur

### ISSUE THREAD

**Issue by hanishassim** [garnele007/SwiftOCR#19]
Hi, I was wondering if this can be used for detecting text and perform action not just get the string, but perform action like blurring on the text.. like car plate number.. can you help shed some light on how to achieve this? Many thanks in advance.

**Comment by garnele007** [comment]
Yes, this should be pretty easy to do. First you have to recognize the image with the numberplate. Then you can take a look at `yourSwiftOCRInstance().currentOCRRecognizedBlobs`. This array contains the bounding boxes of the recognized characters. I would union all these bounding boxes and blur the resulting part of the image.
