### ISSUE TITLE
Port to GPUImage2?

### ISSUE THREAD

**Issue by codeOfRobin** [garnele007/SwiftOCR#2]
Is anyone working on porting this to work with [GPUImage2](https://github.com/BradLarson/GPUImage2)?
Considering that is 100% swift AND Linux compatible, that would greatly expand the usefulness of this project.

**Comment by garnele007** [comment]
I tried it but for me it didn't work. But I can create a new branch for porting.

**Comment by codeOfRobin** [comment]
I'll have a go at it and (hopefullly) have a Pull Request ready ASAP (I'm a student, exams going on at the moment, so will take a while) . Meanwhile, could you please create the branch and add a TODO checklist at the bottom of the README.md?
Thanks for the amazing work!
