### ISSUE TITLE
Configuration(init, or to add a method of settings) SwiftOCR

### ISSUE THREAD

**Issue by REZ1DENT3** [garnele007/SwiftOCR#22]
Thank you, I have started the project. Thanks to your answer #21.

But at the moment I can't replace TesseractOCR with yours, because of the following problems:

1. How to allow reading symbols "., { } [];-+= %..."?
1. The symbol "3" very often reads out as the letter "B"

**Comment by garnele007** [comment]
Currently you can't recognize commas, semicolon and periods but using the training app you should be able to train the other characters.
