### ISSUE TITLE
Adding extra recognized characters to training app errors FFNN

### ISSUE THREAD

**Issue by mhollis1980** [garnele007/SwiftOCR#23]
In the training app when adding extra recognizable character the FFNN barfs with error:
> InvalidAnswerError("Invalid number of outputs given in answer: 37. Expected: 36")

If I remove a value at the front of the string then add a the new character the FFNN finds what it needs to train and successful.

**Comment by garnele007** [comment]
Right now you have to press (in the textfield) enter after adding an extra character. I'll change this behaviour when I have time
