### ISSUE TITLE
Training based on images?

### ISSUE THREAD

**Issue by dxclancy** [garnele007/SwiftOCR#31]
Would it be difficult to mod the training app such that you can give it images for a digit and tell it the correct answer?

**Comment by garnele007** [comment]
Sorry I've read your comment wrong ^^

**Comment by garnele007** [comment]
Do you want to train SwiftOCR with images from digits? (Sorry for closing and opening, I've read your comment wrong ^^)

**Comment by garnele007** [comment]
If yes, you can use the new `generateCharSetFromImages` function to generate training and testing datasets. You would have to edit the `trainWithCharSet` function.

    //Set recognizableCharacters to the characters you want to train
    internal var recognizableCharacters = "0123456789"
    
    public  func trainWithImages() {
        
        let trainingImages = [
            (image: OCRImage(), characters: [Character("0")]),
            (image: OCRImage(), characters: [Character("1")]),
            (image: OCRImage(), characters: [Character("2")]),
            (image: OCRImage(), characters: [Character("3")]) //And so on
        ]
        
        let testingImages = [
            (image: OCRImage(), characters: [Character("0")]),
            (image: OCRImage(), characters: [Character("1")]),
            (image: OCRImage(), characters: [Character("2")]),
            (image: OCRImage(), characters: [Character("3")]) //And so on
        ]
        
        let errorThreshold:Float = 2
        
        let trainData = generateCharSetFromImages(trainingImages, withNumberOfDistortions: 2)
        let testData  = generateCharSetFromImages(testingImages, withNumberOfDistortions: 2)
        
        let trainInputs  = trainData.map({return $0.0})
        let trainAnswers = trainData.map({return $0.1})
        let testInputs   =  testData.map({return $0.0})
        let testAnswers  =  testData.map({return $0.1})
        
        do {
            try globalNetwork.train(inputs: trainInputs, answers: trainAnswers, testInputs: testInputs, testAnswers: testAnswers, errorThreshold: errorThreshold)
            saveOCR()
        } catch {
            print(error)
        }
        
    }

It is important that you provide a lot of training and about a fifth as many testing images, and that the training and testing images are different.

I think this should work. Good luck 😄

**Comment by jokerping** [comment]
hi @garnele007 


I tried it according to your code, but there was an error like this
![image](https://user-images.githubusercontent.com/11515705/38805811-c9df19ea-41a9-11e8-9034-4f934deac976.png)

![image](https://user-images.githubusercontent.com/11515705/38805886-135d3520-41aa-11e8-9ed5-9b02293bde64.png)

please help me，thx
