### ISSUE TITLE
Training not based on selected font in TrainingApp?

### ISSUE THREAD

**Issue by dxclancy** [garnele007/SwiftOCR#32]
Hi, i'm sure I'm wrong, but I've been stepping through the code and it looks like the training images are generated using the font name array in trainingFontNames.

I would have assume that the images would have been generated based on the selectedFontNames being passed in, but as far as i can tell, selectedFontNames, while tracked within the view controller, never affect trainWithCharSet.

Am I missing something?

I've change my file locally:
```
//    private let trainingFontNames  = ["Arial Narrow", "Arial Narrow Bold"]
    public var trainingFontNames  = ["Arial Narrow", "Arial Narrow Bold"]

```
and set this as so;
```
                self.trainingInstance.trainingFontNames = self.selectedFontNames
                self.trainingInstance.trainWithCharSet() { error in

```

**Comment by garnele007** [comment]
Thank you. I never noticed that 😅
