### ISSUE TITLE
Training doesn't appear to work

### ISSUE THREAD

**Issue by staz1000** [garnele007/SwiftOCR#33]
I'm trying to get the iOS app to recognise some text and for the most part it doesn't seem to work. I tried to train using all fonts listed and this made no difference. If I understand things correctly the training some modify the OCR-Network file but Finder tells me the file has not been modified. Am I doing it wrong?

**Comment by garnele007** [comment]
After training you should press `save`. This will save the trained OCR-Network file to your desktop.

**Comment by staz1000** [comment]
Aha I didn't realise, bit of a usability issue with the position of the save button.

Thanks for the quick reply.
