### ISSUE TITLE
Recognising numbers

### ISSUE THREAD

**Issue by staz1000** [garnele007/SwiftOCR#34]
Sorry to open another issue so soon (is an email better?) Despite adding numbers to the training list and adding them to the whitelist I cannot get numbers to be recognised.
![img_1951](https://cloud.githubusercontent.com/assets/5618284/16951302/51b3822c-4dbc-11e6-9632-cdb13781de73.PNG)

BTW we're trying to get this working to capture a Mac address with - seperators, any tips you might have would be appreciated.

**Comment by garnele007** [comment]
I'm sorry that I didn't explain it anywhere correctly. If you train the NN for the characters 0-9 then you have to change `internal var recognizableCharacters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"` to `internal var recognizableCharacters = "0123456789"` in the SwiftOCR.swift file.
You should be able to ignore the separators and add them later.

````swift
func addSeperator(seperator: String, toMACAddress macAddress: String) -> String? {
    guard macAddress.characters.count == 12 else {
        return nil
    }
    
    //0..<6 because every MAC Adsress has 12 characters which are grouped into *6* groups
    var seperatedMACAddressArray = [String]()
    
    for sectionIndex in 0..<6 {
        let substringRange = macAddress.startIndex.advancedBy(sectionIndex * 2)..<macAddress.startIndex.advancedBy(sectionIndex * 2 + 2)
        let sectionSubstring = macAddress.substringWithRange(substringRange)
        seperatedMACAddressArray.append(sectionSubstring)
    }
    
    let macAddress = seperatedMACAddressArray.joinWithSeparator(seperator)
    return macAddress
}

SwiftOCR().recognize(myImage) {recognizedString in
    let macAddress = addSeperator("-", toMACAddress: recognizedString)
}
````
Let me know if it worked. Good luck :-)

**Comment by staz1000** [comment]
Hmm strange, when I change the recognisable characters to ABCDEF0123456789 it works very well but with the original set it doesn't pick up any single number. Why would that be?

**Comment by garnele007** [comment]
The output of the NN looks somewhat like this `[0.01, 0.5, 0.02]`. As you can see `0.5` is the largest output and it's index is 1. After SwiftOCR knows that, it will look what character is at index 1 of `recognizableCharacters` and appends this character to `recognizedString` (which in the end gets returned).

If you set `recognizableCharacters` to `"ABC"` then you would get `B` as your result ,  but if you set it to `"XYZ"` you will get `Y`.

I hope this makes sense (I'm pretty bad at explaining ^^)

**Comment by staz1000** [comment]
Aha, this is why the order of the recognisable characters is so critical!

I got it working perfectly with text on a Word document but we're trying to read the address from a crappy quality screen with low res text. I shall persevere! Thanks.
