### ISSUE TITLE
Question about aspectRatio

### ISSUE THREAD

**Issue by canius** [garnele007/SwiftOCR#38]
I noticed the origin aspectRatio is pushed into end of the data to train.
The ratio value in one of 321 data. I'm wondering if it's really useful for the accuracy.

I've tried a pic which looks like "W" but the ratio is totally different from the ratio trained.It's still recognised as "W".

**Comment by garnele007** [comment]
Hi. i've added the ratio so it is easier to differentiate 1, I and O, 0.

**Comment by canius** [comment]
Thanks for your quick response.
