### ISSUE TITLE
Getting bad OCR on "Simple" Image.

### ISSUE THREAD

**Issue by RollingGoron** [garnele007/SwiftOCR#40]
Can you provide some tips on how to properly train SwiftOCR? Every image I feed it even after training with new fonts, SwiftOCR spits out garbage or an empty array. I feel like I'm not doing something properly. 

These are not difficult images either, something as simple at 3 numbers it can't recognize. What am I doing wrong??

Here is an example image. I've trained the OCR-Network with all fonts.

<img width="695" alt="screen shot 2016-08-30 at 9 17 53 pm" src="https://cloud.githubusercontent.com/assets/2367719/18115812/45ca9a70-6ef7-11e6-82e0-5925667a0638.png">

It seems to skip letters and Tesseract can identify this 100%. What am I doing wrong?

**Comment by garnele007** [comment]
By default SwiftOCR can only recognize uppercase letters and numbers. Your image contains lowercase letters and a special font. If you want to recognize images like these, I would suggest you to train SwiftOCR to recognize this font and lowercase characters.
