### ISSUE TITLE
Number patterns

### ISSUE THREAD

**Issue by danhhgl** [garnele007/SwiftOCR#43]
Hi @garnele007!

This library is useful. But can I recogize digit only and the image has this pattern xxxx xxxx xxxx? Thanks.

**Comment by garnele007** [comment]
Hello,
You can train the NN so it will only recognize digits. If the digits are separated by spaces, recognition won't be a problem.

**Comment by altinselimi** [comment]
@garnele007 So I opened the training app, selected Arial family (Bold, regular etc), and whitelisted only numbers (0123456789), then clicked train. It took some minutes, then I clicked Save. I replaced the OCR-Network file in the framework folder, with the one generated by the train app in the desktop. Next I opened the SwiftOCR Camera project, installed it on my iPhone via xCode. Opened Photoshop on my laptop, typed 18 (Arial font) and added spacing so it could be perfectly clear, and after a lot of [] (empty) recognitions, I finally got a non-empty recognition which was a letter "H". WTF? 

Could you please put up a simple documentation on how to actually use the train app and if we need to change the images inside the "Realistic Training Images" or what?? I think this library has soo much potential if correctly documented.

Thanks.

**Comment by garnele007** [comment]
@altinselimi You have to replace `internal var recognizableCharacters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"` in the SwiftOCR.swift file with `internal var recognizableCharacters = "0123456789"` (0-9 in the same order as you trained the network) or else recognition won't function correctly.

**Comment by altinselimi** [comment]
@garnele007 It recognizes 8 as 0 0 0 0 now. And only works with white characters on black background, else it returns []. Do I have to change the "Realistic Training Images" or anything like that ? I really need to get this going. And if I do, I will make a getting-started tutorial on youtube for this.

**Comment by garnele007** [comment]
@altinselimi You shouldn't have to change the "Realistic Training Images". They are only used to introduce some noise while training. Can you send me the image you are using to test the network?

**Comment by altinselimi** [comment]
@garnele007 I'm actually using my laptop screen, and photoshop document with numbers over it. 
Update: After some tries, it actually is working now, and correctly has recognised the characters last 4 times.

**Comment by garnele007** [comment]
@altinselimi Ok, nice to hear. I asked because if the image is too big or small, recognition can fail.

**Comment by dawand** [comment]
@altinselimi What training app did you use? I am also interested in recognising digits only.
