### ISSUE TITLE
Can't build any of the example project

### ISSUE THREAD

**Issue by ferdinandl007** [garnele007/SwiftOCR#52]
When trying to build any of the example projects I get the following error /Users/ferdinand/Library/Developer/Xcode/DerivedData/SwiftOCR_Training-gomzjvpwejvmqhcbyowxjqloqzmd/Build/Intermediates/GPUImage.build/Debug-iphoneos/Documentation.build/Script-BC552B3A1558C6FC001F3FFA.sh: line 5: /usr/local/bin/appledoc: No such file or directory

Any suggestions how I can fix this thanks in advance

**Comment by geowarsong** [comment]
Try to delete your Xcode's DerivedData folders content, And try to build project again, hope it will help

**Comment by nazrdogan** [comment]
Change  

From 
![screen shot 2016-11-24 at 11 50 56](https://cloud.githubusercontent.com/assets/1672303/20591944/d1ae5ce6-b233-11e6-9f11-216a73e0272b.png)
to
![screen shot 2016-11-24 at 11 51 09](https://cloud.githubusercontent.com/assets/1672303/20591948/d45c1032-b233-11e6-8197-601c06549ea1.png)

**Comment by ferdinandl007** [comment]
I got it working thank you so much for your help!
