### ISSUE TITLE
Read only numbers!!!

### ISSUE THREAD

**Issue by NisalChathuranga** [garnele007/SwiftOCR#53]
I want read only numbers. when try to `internal var recognizableCharacters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"` convert to `internal var recognizableCharacters = "0123456789"` it getting crash or sometime it read character also.
so how to solve?

thank you

**Comment by garnele007** [comment]
If you only want to recognize numbers, I would train the NN. This can be done with the included training app (Put "0123456789" into the textfield). Then replace the old SwiftOCRNet file with the newly generated one.

**Comment by NisalChathuranga** [comment]
Thank you
And when I try to run in iOS application it getting crash also. Should I change this one? `internal var recognizableCharacters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"`

**Comment by garnele007** [comment]
Yes. After replacing the SwiftOCRNet file, you also have to change `recognizableCharacter` to 0123456789.

**Comment by NisalChathuranga** [comment]
Actually I'm studying student. But couldn't found any SwiftOCRNet file. so how do I generate it?
