### ISSUE TITLE
recognize().indexToCharacter() - fatal error: Index out of range

### ISSUE THREAD

**Issue by neoneye** [garnele007/SwiftOCR#55]
The crash happens in its inner function `indexToCharacter()`

>         func indexToCharacter(_ index: Int) -> Character {
>             return Array(recognizableCharacters.characters)[index]
>         }
> 

The `index` is 36.

The `recognizableCharacters` is `ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789`

I use the latest version of SwiftOCR. commit hash: `204e6850149dfd50e507e66edf265fc58cf38178`

I have trained my own `OCR-Network` that I'm using. This is trained with these characters `ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/-`

It doesn't crash if I use the default `OCR-Network` file that is in the SwiftOCR repository.

I like SwiftOCR and find it better than Tesseract.

**Comment by garnele007** [comment]
You have to change `recognizableCharacters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"` to `recognizableCharacters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/-"`.
After that it should work fine.

**Comment by neoneye** [comment]
The default `OCR-Network` that comes with SwiftOCR, has `A-Z0-9` (training characters).

When recognizing I thought that I could use a subset, such as `0-9` (whitelist characters).

With Tesseract, the whitelist characters an be subset of the training characters. 

Instead of crashing, perhaps write an error message, that "whitelist characters must be identical to the training characters."

**Comment by neoneye** [comment]
Hi @garnele007 

Would it be possible to add the `recognizableCharacters` to the `OCR-Network` file?


```
///The characters the globalNetwork can recognize.
///It **must** be in the **same order** as the network got trained
public var recognizableCharacters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
///The FFNN network used for OCR
public var globalNetwork = FFNN.fromFile(Bundle(for: SwiftOCR.self).url(forResource: "OCR-Network", withExtension: nil)!)!
```
