### ISSUE TITLE
training ?

### ISSUE THREAD

**Issue by raphaels17** [garnele007/SwiftOCR#59]
Hello 

I am trying to understand what do to when the app is trained ? how do I get back the training neural network to the camera app ?

Also in the SwiftOCR Camera app there is also SwiftOCRTraining, which is never used what is its purpose?

**Comment by garnele007** [comment]
Hi @raphaels17 

After training you can replace the `SwiftOCR/OCR-Network` file with the `OCR-Network` file found on your desktop.

The SwiftOCRTraining file is only needed for training. It is not required for recognition.

**Comment by raphaels17** [comment]
Thanks very helpful and the result are indeed promising. Some blobs are not being recognized and therefore skipped unfortunately.
This being said I'd like to enhance the accuracy. what would you suggest will increase the numberOfTrainImages be of any use or is 500 a good enough number?
More generally would you have any documentation you believe I should start with to gain a better understanding of your code ?

Thanks  a lot for the library is pretty sweet

**Comment by garnele007** [comment]
You can experiment with increasing the number of training images, but I don't know how it will affect the accuracy.

I don't really have any kind of documentation except for the comments in the code, but I would suggest you to read this [wikipedia article](https://en.wikipedia.org/wiki/Connected-component_labeling) about connected-component labelling. I use CCL for character segmentation.

**Comment by raphaels17** [comment]
Thanks on to it!
