### ISSUE TITLE
Image Training and Error

### ISSUE THREAD

**Issue by magonicolas** [garnele007/SwiftOCR#67]
Hello, this seems awesome, I can't make it work, I build for example iOs version and It gives me the following error "/Users/nicolaspalacios/Library/Developer/Xcode/DerivedData/SwiftOCR_Camera-gxrakixxmfxwzmfrklrdfujhvzsp/Build/Intermediates/GPUImage.build/Debug-iphonesimulator/Documentation.build/Script-BC552B3A1558C6FC001F3FFA.sh: line 5: /usr/local/bin/appledoc: No such file or directory"
Also, how can I do it so I could gave it images and categorize images based on training for something different than letters? For example Car Colores, shapes, etc?

**Comment by garnele007** [comment]
@magonicolas Did you try cleaning the build folder? With SwiftOCR you can't categorise images but I can suggest you to create a Convolutional Neural Network using a framework like [MXNet](https://github.com/dmlc/mxnet).

**Comment by magonicolas** [comment]
Yes, I have just tried, and it didn't work. Thanks for the example, seems to do What I need, You know something like that for swift?

**Comment by garnele007** [comment]
As far as I know there is no CNN framework in Swift, but you can use MXNet it with objective-c++.([https://github.com/pppoe/WhatsThis-iOS](https://github.com/pppoe/WhatsThis-iOS))
