### ISSUE TITLE
Despite duration or # of fonts trained, OCR-Network maxes at 930kb?

### ISSUE THREAD

**Issue by longhoanguyen** [garnele007/SwiftOCR#97]
Hello,

I am using the macOS training app, and no matter how many fonts I select for training, the resulting OCR-Network file maxes out at 930kb, even when I change the errorThreshold or # of training images.

Is this intended behavior? I notice that the accuracy doesn't improve much despite longer training or # of images, possibly because of the limited OCR-Network size?

Thanks!

**Comment by garnele007** [comment]
The duration doesn't hang together with the OCR-Network size. The size is dictated by the number of neutrons in the neural network.
